### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by Kulu-M** [bolorundurowb/vCardLib#1]
Hello,

when using your sample code the import is not working for me. The object is just empty even though the vcf has content. Do i have to do anything else except your example code? 

(Net 4.6 and V.1.1.1 of vCardLib.dll from NuGet)

Thanks

**Comment by bolorundurowb** [comment]
I'm sorry about that, what version of vCard did you feed into the library?  For now, it only supports version 2.1

**Comment by Kulu-M** [comment]
I used all the examples from [wikipedia](https://de.wikipedia.org/wiki/VCard#Beispiele), but it was not working. The objects were empty.

**Comment by bolorundurowb** [comment]
Thanks for opening this issue. I'll test it with the Wikipedia values and fix it

**Comment by bolorundurowb** [comment]
i think I have it fixed now
