### ISSUE TITLE
Issue with Property BirthDay of vCard class

### ISSUE THREAD

**Issue by mixerp** [bolorundurowb/vCardLib#14]
Shouldn't the type of property `BirthDay` be `DateTime?` instead of `DateTime`? IMHO, returning `{1/1/0001 12:00:00 AM}` when the vcard file does not have this information is bit wrong.

**Comment by bolorundurowb** [comment]
I agree @mixerp I'll adjust it in the next release

**Comment by bolorundurowb** [comment]
Fixed in current release cc @mixerp
