### ISSUE TITLE
Wrong First Name and Surname in Serializing

### ISSUE THREAD

**Issue by mixerp** [bolorundurowb/vCardLib#15]
The first name and last name during serialization (and maybe deserialization) is wrong. The current output of `John Doe` is:

```
N:John;Doe;
FN:John Doe
```
which should be:

```
N:Doe;John;;;
FN:John Doe
```
As per the Rfc2426, the value for token `N` is:

```
Family; Given; Middle; Prefix; Suffix
```

Lastly, IMHO, the `vCard` class should have these additional properties:
- Middle Name
- Prefix
- Suffix

For [Frapid framework](https://github.com/frapid/frapid), we're already using this library and would like to offer a helping hand.

- Would you like us to fix these issues and send pull requests?
- Once you accept the pull requests, how long would it normally take for it to appear in nuget?

**Comment by bolorundurowb** [comment]
@mixerp Please PR's are very welcome. Once a PR is created, it would be on Nuget within 24 hours

**Comment by bolorundurowb** [comment]
Fixed in current release. cc @mixerp
