### ISSUE TITLE
Кирилица

### ISSUE THREAD

**Issue by Q2Baklan** [bolorundurowb/vCardLib#21]
Данное решение не поддерживает кирилицу для Android.
В целом отсутсвует поддержка Encoding 👎 

Взял себе на машину допилил Encoding для ios создаю Encoding.Unicode, а вот Android не получается ни как организовать.

**Comment by bolorundurowb** [comment]
@Q2Baklan Thanks for raising this issue. I will look into encoding ASAP.

**Comment by Q2Baklan** [comment]
Коллеги, хочу заметить сборка не подписана, не знаю на сколько это критично для NuGet публикации, но для прикручивания к портальному решению (MS Sharepoint) сборку пришлось подписать. Еще хотелось бы видеть зачетные примеры как правильно сгенерить vcard для Android на Кирилице к примеру или прочие.

**Comment by bolorundurowb** [comment]
@Q2Baklan signing isn't required for publishing to NuGet. The advantage of open source code is that you can go through and check if there is anything malicious embedded in there.

**Comment by bolorundurowb** [comment]
@Q2Baklan I have looked through the codebase and I can't see where Encoding is needed. Could you point me in the right direction?

**Comment by Q2Baklan** [comment]
Вот что у меня получилось: 
1) для iOS
![image](https://user-images.githubusercontent.com/7767153/28859683-79ec6dba-7761-11e7-8a1e-f4275e12e715.png)
2)Промежуточный файл для Android
![image](https://user-images.githubusercontent.com/7767153/28859737-c73bd560-7761-11e7-994d-7a805b9d63b9.png)
3)Промежуточный пересохраняю (в другую кодировку) в Финальный файл для Android
![image](https://user-images.githubusercontent.com/7767153/28859773-0559c83e-7762-11e7-8657-1583ada9e3a1.png)

Для Android 
перед добавлением vCardCollection.Add() строку перекодировал так 
![image](https://user-images.githubusercontent.com/7767153/28859976-2d8af354-7763-11e7-8e2e-824b7d9e8b12.png), для vCardCollection.Save(...., Encoding) организовал
![image](https://user-images.githubusercontent.com/7767153/28860361-fc951d2c-7764-11e7-8c87-3e7d4335ad8c.png)
 
![image](https://user-images.githubusercontent.com/7767153/28860422-3cc48ab8-7765-11e7-89f0-59b9cffcd7a1.png)

![image](https://user-images.githubusercontent.com/7767153/28860313-d09ecccc-7764-11e7-9add-f50be7a98fbe.png)
 

получал промежуточный файл
далее для Android перекодировал промежуточный в финальный
так (нашел в MSDN):

`
public static void ConvertFileEncoding(String sourcePath, String destPath, Encoding sourceEncoding, Encoding destEncoding)
        {
        // If the destination's parent doesn't exist, create it.
        String parent = Path.GetDirectoryName(Path.GetFullPath(destPath));
        if (!Directory.Exists(parent))
         Directory.CreateDirectory(parent);
        
        // If the source and destination encodings are the same, just copy the file.
        if (sourceEncoding == destEncoding)
        {
            File.Copy(sourcePath, destPath, true);
            return;
        }

        // Convert the file.
        String tempName = null;
        try
        {
            tempName = Path.GetTempFileName();

            using (StreamReader sr = new StreamReader(sourcePath, sourceEncoding, false))
            {
                using (StreamWriter sw = new StreamWriter(tempName, false, destEncoding))
                {
                    int charsRead;

                    char[] buffer = new char[128 * 1024];

                    while ((charsRead = sr.ReadBlock(buffer, 0, buffer.Length)) > 0)
                    {
                        sw.Write(buffer, 0, charsRead);
                    }
                }
            }
            File.Delete(destPath);
            File.Move(tempName, destPath);
        }
        finally{
            File.Delete(tempName);
        }
    }
`

**Comment by bolorundurowb** [comment]
@Q2Baklan If I understand you correctly, you have had to implement Encoding on your own and you want both vcf file reading encoding and writing encoding. Am I correct?

**Comment by Q2Baklan** [comment]
Что бы Android правильно читал Кириллицу , пришлось в библиотеку vCardLib в метод Save  добавить vCardCollection.Save(...., **Encoding**), в противном случае либо не читалась структура файла (как vcard), либо не читалась Кириллица. Ведь сформированный файл состоял из Пример: ".... FN:Фамилия ...." (сочетания Латиницы и Кириллицы).

**Comment by bolorundurowb** [comment]
So, @Q2Baklan in your opinion `Unicode` Encoding would enable the storing and reading of Non Latin characters? I would add that in the next release. I would begin work on it today _ceteris paribus_

**Comment by Q2Baklan** [comment]
В общем то да, позволяет, но и как писал выше было бы не плохо показать пример с реализацией НЕ ЛАТИНИЦЫ. Т.к. еще необходимо обрабатывать само значение (к примеру Фамилия Имя Отчество).

**Comment by bolorundurowb** [comment]
Hey @Q2Baklan I have implemented checking the file Encoding when reading the file and then allows for specifying the encoding when saving the vCard on the `dev` branch. I need a `vcf` file with cyrillic characters that i can use to test the changes I made. Also if there is something I missed, please feel free to send a PR in.
