### ISSUE TITLE
vCardCollection save - wrong format

### ISSUE THREAD

**Issue by pircjernej** [bolorundurowb/vCardLib#24]
When I try to save collection of vCards the END:VCARD
and new BEGIN:VCARD are writen in the same line,
and when I try to imported that file I get error.

If I manualy make linebreke with text editor and save file i can import multiple files...

my sample write code:

                        var cardList = new vCardCollection();

                        for (int i = 1; i < result.Tables[0].Rows.Count; i++)
                        {
                            DataRow row = result.Tables[0].Rows[i];

                            var card = new vCard();
                            card.Version = vCardLib.Helpers.Version.V3;
                            card.GivenName = row[0].ToString();
                            card.FamilyName = row[1].ToString();
                            var vca = new vCardLib.Models.EmailAddress();
                            vca.Email = new System.Net.Mail.MailAddress(row[2].ToString());
                            card.EmailAddresses.Add(vca);
                            var phone = new vCardLib.Models.PhoneNumber();
                            phone.Number = row[3].ToString();
                            card.PhoneNumbers.Add(phone);
                            cardList.Add(card);

                        }

                        cardList.Save("test.vcf", vCardLib.Helpers.Version.V3, vCardLib.Helpers.WriteOptions.Overwrite);

**Comment by bolorundurowb** [comment]
@pircjernej I would try to replicate this.

**Comment by bolorundurowb** [comment]
@pircjernej I have released an update with a fix
