### ISSUE TITLE
Xamarin iOS deployment

### ISSUE THREAD

**Issue by Diraekt** [bolorundurowb/vCardLib#32]
Hello

Because of your dependency of "CoreCompat.System.Drawing.v2" it's not possible to deploy on a real iOS Device, the linker will fail with the following message: "carbon framework not found"...

I removed this dependency (remove photo support) for the moment to get it working.

Best Greetings

**Comment by bolorundurowb** [comment]
@Diraekt for v3, I would take a look at implementing the image support with something that supports the linker or just spit out a byte array instead

**Comment by bolorundurowb** [comment]
hey @Diraekt sorry for not updating this, but the dependence on System.Drawing has been removed.
