### ISSUE TITLE
float.Parse in GetVcardFromDetails isn't working if decimal seperator != .

### ISSUE THREAD

**Issue by gitalexa** [bolorundurowb/vCardLib#33]
version = float.Parse(versionString.Replace("VERSION:", "").Trim());

results in wrong results if in CultureSettings is defined that the decimal seperator is not "." as in german (we using ,)

i replaced it with:

            float version;

            string dSep = CultureInfo.CurrentUICulture.NumberFormat.NumberDecimalSeparator;
            if (dSep.Equals(",")) {

                version = float.Parse(versionString.Replace("VERSION:", "").Trim().Replace(".", ","));
            } else {

                version = float.Parse(versionString.Replace("VERSION:", "").Trim());
            }

**Comment by bolorundurowb** [comment]
Thanks for pointing this out @gitalexa
