### ISSUE TITLE
all vCard properties null

### ISSUE THREAD

**Issue by gottscbe** [bolorundurowb/vCardLib#4]
I tried the library with a vcf-file, which contains multiple vcf-cards. There will be created multiple vCard objects, but all their properties are null (although, they are NOT null in the vcf-file for sure).
On example vcard:

BEGIN:VCARD
VERSION:3.0
FN:
N:;;;;
EMAIL;TYPE=INTERNET:a@b.com
END:VCARD

**Comment by bolorundurowb** [comment]
Thanks for the feedback. Can you give a small sample of the vcf file you sent as input? You can just pick out the first two contacts. Also, what version of the library are you using?

**Comment by gottscbe** [comment]
Sure, here's an example file:
[test.zip](https://github.com/bolorundurowb/VCF-Reader/files/392033/test.zip)

I use version 2.0.0 of the library, see this excerpt of my packages.config file:
 `<package id="vCardLib.dll" version="2.0.0" targetFramework="net452" />`

**Comment by gottscbe** [comment]
Sorry, closed the issue accidentially. Re-opened it now.

**Comment by bolorundurowb** [comment]
I will look into it now

**Comment by bolorundurowb** [comment]
This is what I got from using a GUI tool that makes use of v2 of the library
![image](https://cloud.githubusercontent.com/assets/10448811/17276206/c3742e0a-5719-11e6-8764-5285142f00ac.png)

I placed a breakpoint in the library code and got these screenshots out
_First Contact_
![first contact fw](https://cloud.githubusercontent.com/assets/10448811/17276246/f3cdb19c-571a-11e6-8b2d-9acbe6a012f3.png)

_Second Contact_
![second contact 1 fw](https://cloud.githubusercontent.com/assets/10448811/17276248/0c5f89e2-571b-11e6-81b2-24adf3436dfa.png)

![second contact 2 fw](https://cloud.githubusercontent.com/assets/10448811/17276249/0fb2b36c-571b-11e6-9653-14fca715bc67.png)

**Comment by gottscbe** [comment]
That's really strange. I used the lib this way:

```
            var vCardCollection = vCard.FromFile(vcfFilePath);
            foreach (vCard vCard in vCardCollection)
            {
                var contactVm = new ContactVm(vcfFilePath, vCard);
                this.Contacts.Add(contactVm);
            }
```

This is the same code-snippet in debugger when reading the test.vcf file (see above):
![image](https://cloud.githubusercontent.com/assets/16079080/17277384/c97640cc-5741-11e6-9e57-6d12de367740.png)

Please find my entire app attached:
[ContactManager.zip](https://github.com/bolorundurowb/VCF-Reader/files/392477/ContactManager.zip)

**Comment by gottscbe** [comment]
Just tried your VCF Reader 1.2 here on my PC. I only see two empty rows in the grid, no contents:
![image](https://cloud.githubusercontent.com/assets/16079080/17277410/7bdaf3ac-5742-11e6-8199-dbaddfd76ad3.png)

**Comment by bolorundurowb** [comment]
This is a quite interesting bug we have on our hands here, I'll look through your code and get back to you. In the mean time, try the debug version of the library
[vCardLib.zip](https://github.com/bolorundurowb/VCF-Reader/files/394899/vCardLib.zip)

**Comment by bolorundurowb** [comment]
This is the output I got.
![my output](https://cloud.githubusercontent.com/assets/10448811/17321049/7fa1e796-588e-11e6-84ba-8a5105fea65c.png)

**Comment by fatihbahceci** [comment]
I found the solution.
The reason is: cultureinfo. 
When decimal separator is "," in current culture; version becomes 2.1 to 21;
The solution is :
 `Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-GB");`
