### ISSUE TITLE
'Input string was not in a correct format.'

### ISSUE THREAD

**Issue by dvdobrovolskiy** [bolorundurowb/vCardLib#41]
BEGIN:VCARD
VERSION:2.1
N:;.;;;
FN:.
END:VCARD
BEGIN:VCARD
VERSION:2.1
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:xxxxxxx;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLExxxxxx
TEL;CELL:+70000000000
END:VCARD

**Comment by bolorundurowb** [comment]
I just pushed an update. I ran this sample with the updated library and did not encounter any exceptions. 
I would close this, for now, feel free to reopen if the error persists
