### ISSUE TITLE
Does not parse encoded image in 'v3.vcf'

### ISSUE THREAD

**Issue by jbrockerville** [bolorundurowb/vCardLib#45]
Ran with `vCardLib/vCardLib.Tests/v3.vcf`. The pictures list only contains the two URL photos.

**Comment by bolorundurowb** [comment]
@jbrockerville this issue was referenced in PR #47 did that fix this issue?

**Comment by bolorundurowb** [comment]
@jbrockerville this should have been addressed in #47 or in the versions greater than 5.0.0. Try it out and if the issue persists, you can reopen this
