### ISSUE TITLE
System.NotImplementedException when serializing v4 card

### ISSUE THREAD

**Issue by timdinh** [bolorundurowb/vCardLib#54]
Hello, We would like to report that a `System.NotImplementedException` is thrown when attempting to serialize a `vCard` instance that had `Version = vCardVersion.V4`.

The issue exists in version up to 4.0.1

**Comment by bolorundurowb** [comment]
@timdinh the recently published version 5.0.0 and above have vCard v4 support. I'll close this ticket now
