### ISSUE TITLE
Serialize multiple vcard generate wrong start/end frame

### ISSUE THREAD

**Issue by rallets** [bolorundurowb/vCardLib#55]
Hi, I'm serializing multiple vcards, and the Start/End frame is generated on the same line, breaking the import in Android.
Basically it generates a vard that looks like
```
[...]
GENDER:None
END:VCARDBEGIN:VCARD
VERSION:3.0
[...]
```

but I'm expecting
```
[...]
GENDER:None
END:VCARD
BEGIN:VCARD
VERSION:3.0
[...]
```

Any tips? 
Thank you

**Comment by rallets** [comment]
@bolorundurowb I have sent a PR to fix these two issues, with related unit tests, could you take a look? are you interested in merging them?
Thank you

**Comment by bolorundurowb** [comment]
Approved the PR, but there is a failing test due to the line endings `\r` and the test runner expecting `\r\n`. You can replace the line endings in your string with `Envrionment.NewLine`

**Comment by nordfish-it** [comment]
@bolorundurowb I updated the PR and it looks the tests are passing now. Can you merge and generate a new release?
Thank you!

**Comment by rallets** [comment]
Tks!
