### ISSUE TITLE
vCardLib Documentation points back to VCF-Reader library with the Source button.

### ISSUE THREAD

**Issue by Swimburger** [bolorundurowb/vCardLib#59]
At first I thought this project was unmaintained because the "SOURCE" button points to the archived VCF-Reader library
![Screen Shot 2022-07-05 at 3 45 36 PM](https://user-images.githubusercontent.com/3382717/177403948-a9268b76-cf61-4013-91fe-5673e11bcf4a.png)
.

I think this button should link to this GitHub repo, right?

**Comment by bolorundurowb** [comment]
That is correct, I need to remove the gh page entirely as it is outdated
