### ISSUE TITLE
Identify better URLs when they have metadata

### ISSUE THREAD

**Issue by ManolisKoufidakis** [bolorundurowb/vCardLib#68]
Hi,

When the url is in the form of `URL;WORK:www.foo.com` then the library returns it as `"Url": "URL;WORK:www.foo.com",` in the vcard object. When the url is in the form of `URL:www.foo.com` then the library returns it as `"Url": "www.foo.com",` in the vcard object. 

I think that the first case should be supported just like the second. I can open a PR if there are no objections. 

Thank you

**Comment by bolorundurowb** [comment]
Hi @ManolisKoufidakis thanks, I'll address it. This will mean a major version change as it'll introduce breaking changes
