### ISSUE TITLE
Deserializer.FromFile throws file not found when file exists

### ISSUE THREAD

**Issue by anmatr** [bolorundurowb/vCardLib#69]
In version 5.0.1 (maybe even earlier) the call to vCardDeserializer.FromFile(<fileName>) throws a "file not found" but the file exists. The code shows that the line writes if (File.Exists(fileName)). So the ! (not) is missing.

Additionally could the log details be changed as the missing file name would not be shown from the current log file.

**Comment by anmatr** [comment]
I see a PR is already in the pipeline for this. Doesn't seem to be merged yet.

**Comment by bolorundurowb** [comment]
@anmatr This has been addressed in PR #70 and should be published to Nuget in a few minutes as version 5.0.2
