### ISSUE TITLE
Can not import lib in vs2013

### ISSUE THREAD

**Issue by lasseo** [bolorundurowb/vCardLib#7]
Install-Package : ZIP archive contains unsupported data structures.
At line:1 char:16
+ Install-Package <<<<  vCardLib.dll
    + CategoryInfo          : NotSpecified: (:) [Install-Package], NotSupportedException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by bolorundurowb** [comment]
Hello @lasseo I don't have VS2013, but I tried installing the library on VS15 Express Preview 5 and it installed without issues. Please let me know if you are still experiencing issues with the installation within a week. So I can know whether to leave the issue open or close it.

**Comment by bolorundurowb** [comment]
Hello @lasseo Since I haven't heard from you in three weeks, I'll close this issue. If the issue crops up, re-open the issue
